apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: netology-pods
  namespace: default
subjects:
- kind: User
  name: netology
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: netology
  apiGroup: rbac.authorization.k8s.io
